version: "3.0"
services:
  video:
    image: streamberry:1.0.1
    restart: always
    container_name: container_streamberry
    env_file:
     - streamberry.env
    ports:
     - 8888:8888
    devices:
     - /dev/video0:/dev/video0
